### ISSUE TITLE
Include .config directory?

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-skeleton#6]
Should we include a `.config/load.php` out of the box to encourage best practices for manual configuration? We can then also include it in the `composer.json` out of the box.

@joehoyle ?

**Comment by joehoyle** [comment]
Hmm unless we specifically have reason to, I'd rather not. It's more there for backwards compat, I'd like to see most new projects either pass custom configs directly in the `extra.platform` field, or use a more specifically named config file `redirects.php` etc.

**Comment by rmccue** [comment]
You still need an entry point, no? Or are you thinking every config file would be added to the autoload?

**Comment by roborourke** [comment]
Config in the `composer.json` is one step but there are plenty of times you'd want to set constants, either because certain plugins make use of them or because they're internal WP constants like post revision limits etc. Some constant values might be dynamic and we even provide docs for adding geolocation headers etc which would presumably go under `.config/load.php`.

I'm 👍 for reducing the number of steps and work engineers need to do.

I'm 👎 on using autoload for PHP config files too because the core functions such as `get_environment_type()` may not yet be available.

**Comment by roborourke** [comment]
`.config/load.php` is included explicitly now and documented. It's an escape hatch we want to discourage so we won't provide it out of the box.
